language: python
python:
- '3.6'
install: 
script: echo "Skip tests"
after_success: codecov
deploy:
  provider: pypi
  user: illusional
  password:
    secure: IVJ7+7PyFHp6tHE+7GrbGjUGu01zO7y27x5SISTCk/LjeVo93keNbAe2pVZ6JosJ6fFS4iL99qgBj+NTCYyBMh3Nq2ZJpio5L6pFR0fAaMkR2x2LwwgFH+Y8ZicM0oXBNWNDDg/V0A9O4TcYNlxOyjL8VRUmjN0irtbVWxULr3SKnBl9tiDOxixi5jT6h3hPiSUEAxmN68Ayopm/fuVcO36LBYmMkAAmNIQoKB0vBWPeice+W8u5Dbvi7tuwNtVaB7WyQsfhzgWDQVHmEIu5qrAqAbehA/qXCdT02rFWE4w0LTMGmZiaQ9yKPVQAHY21FNzkK58/QVpF8gMrCjysagT3irS5TfSUzTuyajDMWDGZkYtz4hMxO2kCwX9OUkbn0x5kepONxgbd1aHe0pAmLEJj+bG2+3xBa+iFYb0SnWhj05DgjO4bWDIDykapzr7TG1DnIw0tJuPHj9hB+/Hl52P1Z1yd2urMtQeYDf7GVFtXzBO08SfcqZTTN5PIzjMkUz0VRu7prGwG0S+6jp7H6Mu66C113ficZi01J3YgvvirFIo9boCSpXS2ly/QRrFZ3PqNCqcAQSOn9E3zAMBwxMBOCdAh8+m4+7+7MFYQnyI3F/zV53Rcu4u/4Bmm2Le6Il+Wv9tMEjTgOmE28t7aU2vuh25be82/DSA0s3Jlt+4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: PMCC-BioinformaticsCore/janis-pipelines
